# Generated by Django 5.2 on 2025-04-03 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tanggal_lahir', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mk', models.CharField(max_length=10, unique=True)),
                ('nama_mk', models.CharField(max_length=200)),
                ('jumlah_pertemuan', models.IntegerField(default=16)),
            ],
        ),
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=500)),
                ('nama_pengguna', models.CharField(max_length=500, unique=True)),
                ('palm_kiri', models.CharField(blank=True, max_length=500, null=True)),
                ('palm_kanan', models.CharField(blank=True, max_length=500, null=True)),
                ('wajah', models.CharField(blank=True, max_length=500, null=True)),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scanA.mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalPresensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanA.kelas')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanA.matakuliah')),
            ],
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Hadir', 'Hadir'), ('Alpha', 'Alpha'), ('Izin', 'Izin'), ('Sakit', 'Sakit')], default='Alpha', max_length=10)),
                ('waktu_presensi', models.DateTimeField(auto_now_add=True)),
                ('jadwal_presensi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanA.jadwalpresensi')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanA.mahasiswa')),
            ],
        ),
    ]
